export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'
export const USER_LOADED='USER_LOADED'
export const AUTH_ERROR='AUTH_ERROR'
export const LOGIN_FAIL='LOGIN_FAIL'
export const LOGOUT='LOGOUT'
export const CLEAR_ERRORS='CLEAR_ERRORS'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const PASS_CHANGE = 'PASS_CHANGE'
export const PASS_CHANGE_ERROR = 'PASS_CHANGE_ERROR'
export const PAYAVENUES_ERROR = 'PAYAVENUES_ERROR'
export const PAYAVENUES = 'PAYAVENUES'

export const APPLY_LOAN = "APPLY_LOAN"
export const APPLY_LOAN_ERROR = "APPLY_LOAN_ERROR"

export const GET_UNPROCESSED_LOANS = "GET_UNPROCESSED_LOANS"
export const GET_UNPROCESSED_LOANS_ERROR = "GET_UNPROCESSED_LOANS_ERROR"

export const GET_ONE_UNPROCESSED_LOAN = "GET_ONE_UNPROCESSED_LOAN"
export const GET_ONE_UNPROCESSED_LOAN_ERROR = "GET_ONE_UNPROCESSED_LOAN_ERROR"


export const DENY_LOAN = "DENY_LOAN"
export const DENY_LOAN_ERROR = "DENY_LOAN_ERROR"

export const APPROVE_LOAN = "APPROVE_LOAN"
export const APPROVE_LOAN_ERROR = "APPROVE_LOAN_ERROR"

export const GET_USER_LOANS = "GET_USER_LOANS"
export const GET_USER_LOANS_ERROR = "GET_USER_LOANS_ERROR"


export const MAKE_PAYMENT = "MAKE_PAYMENT"
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR"